Creative tab proposal
MinecraftModDevelopmentMods/BaseMetals pull request #125
Opened 2017-04-24 20:21 UTC by dshadowwolf

Proposal for making creative tabsthrough MMDLib a per-mod setup and mostly severing them from any underlying structure in MMDLib. The final part of that is a WIP that is part of why this proposal is not eing suggested fro a direct pull.

1) Remove final ties to any specific naming in MMDLib - this will likely require some architecture changes. (I'm out of ideas on how to make this happen in a maintainable and good manner)
2) The setup for the "Tab Icon Item" should be changed to a Callable<> or similar to match the code and style in MMDLib - I'm not ashamed to say that I've not worked with this in the past and am unsure of how to make it work. (Though... if Callable<> is like a Promise, then... it won't be too hard)

2017-04-24 21:36 UTC, jriwanek requested changes

2017-04-24 21:36 UTC, jriwanek commented on src/main/java/com/mcmoddev/basemetals/init/Items.java
> +			FuelRegistry.addFuel(Oredicts.NUGGET+"_charcoal", 200);
No need for the Oredict change, was temporarily broken, now fixed.

2017-04-24 21:36 UTC, jriwanek commented on src/main/java/com/mcmoddev/basemetals/init/Items.java
> +			FuelRegistry.addFuel(Oredicts.NUGGET+"_coal", 200);
No need for the Oredict change, was temporarily broken, now fixed.

2017-04-24 21:36 UTC, jriwanek commented on src/main/java/com/mcmoddev/lib/init/Blocks.java
> +	protected static Block createPlate(MMDMaterial material, CreativeTabs tab) {
Needs oredict stuff put back

2017-04-24 21:36 UTC, jriwanek commented on src/main/java/com/mcmoddev/lib/init/Blocks.java
> +	protected static Block createBars(MMDMaterial material, CreativeTabs tab) {
Needs oredict stuff put back

2017-04-24 21:36 UTC, jriwanek commented on src/main/java/com/mcmoddev/lib/init/Blocks.java
> +				addBlock(new BlockMMDBlock(material, glow, true), Names.BLOCK, material, tab);
Needs oredict stuff put back

2017-04-24 21:36 UTC, jriwanek commented on src/main/java/com/mcmoddev/lib/init/Blocks.java
> +	protected static Block createButton(MMDMaterial material, CreativeTabs tab) {
Needs oredict stuff put back

2017-04-24 21:36 UTC, jriwanek commented on src/main/java/com/mcmoddev/lib/init/Blocks.java
> +	protected static Block createLever(MMDMaterial material, CreativeTabs tab) {
Needs oredict stuff put back

2017-04-24 21:36 UTC, jriwanek commented on src/main/java/com/mcmoddev/lib/init/Blocks.java
> +	protected static BlockSlab createSlab(MMDMaterial material, CreativeTabs tab) {
Needs oredict stuff put back (comment)

2017-04-24 21:36 UTC, jriwanek commented on src/main/java/com/mcmoddev/lib/init/Blocks.java
> +	protected static BlockSlab createDoubleSlab(MMDMaterial material, CreativeTabs tab) {
Needs oredict stuff put back (comment)

2017-04-24 21:36 UTC, jriwanek commented on src/main/java/com/mcmoddev/lib/init/Blocks.java
> +	protected static Block createStairs(MMDMaterial material, CreativeTabs tab) {
Needs oredict stuff put back

2017-04-24 21:36 UTC, jriwanek commented on src/main/java/com/mcmoddev/lib/init/Blocks.java
> +	protected static Block createWall(MMDMaterial material, CreativeTabs tab) {
Needs oredict stuff put back

2017-04-24 21:36 UTC, jriwanek commented on src/main/java/com/mcmoddev/lib/init/Blocks.java
> +	protected static Block createOre(MMDMaterial material, CreativeTabs tab) {
Needs oredict stuff put back

2017-04-24 21:36 UTC, jriwanek commented on src/main/java/com/mcmoddev/lib/init/Blocks.java
> +	protected static Block createEndOre(MMDMaterial material, CreativeTabs tab) {
Needs oredict stuff put back

2017-04-24 21:36 UTC, jriwanek commented on src/main/java/com/mcmoddev/lib/init/Blocks.java
> +	protected static Block createNetherOre(MMDMaterial material, CreativeTabs tab) {
Needs oredict stuff put back

2017-04-24 21:36 UTC, jriwanek commented on src/main/java/com/mcmoddev/lib/init/Blocks.java
> +	protected static BlockDoor createDoor(MMDMaterial material, CreativeTabs tab) {
Needs oredict stuff put back (comment)

2017-04-24 21:36 UTC, jriwanek commented on src/main/java/com/mcmoddev/lib/init/Blocks.java
> +	protected static Block createTrapDoor(MMDMaterial material, CreativeTabs tab) {
Needs oredict stuff put back

2017-04-24 21:36 UTC, jriwanek commented on src/main/java/com/mcmoddev/lib/init/Items.java
> +	protected static Item createCrystal(MMDMaterial material, CreativeTabs tab) {
Needs oredict stuff put back

2017-04-24 21:36 UTC, jriwanek commented on src/main/java/com/mcmoddev/lib/init/Items.java
> +	protected static Item createGem(MMDMaterial material, CreativeTabs tab) {
Needs oredict stuff put back

2017-04-24 21:36 UTC, jriwanek commented on src/main/java/com/mcmoddev/lib/init/Items.java
> +	protected static Item createIngot(MMDMaterial material, CreativeTabs tab) {
Needs oredict stuff put back

2017-04-24 21:36 UTC, jriwanek commented on src/main/java/com/mcmoddev/lib/init/Items.java
> +	protected static Item createNugget(MMDMaterial material, CreativeTabs tab) {
Needs oredict stuff put back

2017-04-24 21:36 UTC, jriwanek commented on src/main/java/com/mcmoddev/lib/init/Items.java
> +	protected static Item createPowder(MMDMaterial material, CreativeTabs tab) {
Needs oredict stuff put back

2017-04-24 21:36 UTC, jriwanek commented on src/main/java/com/mcmoddev/lib/init/Items.java
> +	protected static Item createBlend(MMDMaterial material, CreativeTabs tab) {
Needs oredict stuff put back

2017-04-24 21:36 UTC, jriwanek commented on src/main/java/com/mcmoddev/lib/init/Items.java
> +	protected static Item createRod(MMDMaterial material, CreativeTabs tab) {
Needs oredict stuff put back (missing one entry)

2017-04-24 21:36 UTC, jriwanek commented on src/main/java/com/mcmoddev/lib/init/Items.java
> +	protected static Item createGear(MMDMaterial material, CreativeTabs tab) {
Needs oredict stuff put back (missing one entry)

2017-04-24 21:36 UTC, jriwanek commented on src/main/java/com/mcmoddev/lib/init/Items.java
> +	protected static Item createArrow(MMDMaterial material, CreativeTabs tab) {
Needs oredict stuff put back

2017-04-24 21:36 UTC, jriwanek commented on src/main/java/com/mcmoddev/lib/init/Items.java
> +	protected static Item createBolt(MMDMaterial material, CreativeTabs tab) {
Needs oredict stuff put back

2017-04-24 21:36 UTC, jriwanek commented on src/main/java/com/mcmoddev/lib/init/Items.java
> +	protected static Item createSmallBlend(MMDMaterial material, CreativeTabs tab) {
Needs oredict stuff put back

2017-04-24 21:36 UTC, jriwanek commented on src/main/java/com/mcmoddev/lib/init/Items.java
> +	protected static Item createSmallPowder(MMDMaterial material, CreativeTabs tab) {
Needs oredict stuff put back

2017-04-24 21:36 UTC, jriwanek commented on src/main/java/com/mcmoddev/lib/init/Items.java
> +	protected static Item createShield(MMDMaterial material, CreativeTabs tab) {
Needs oredict stuff put back

2017-04-24 21:36 UTC, jriwanek commented on src/main/java/com/mcmoddev/lib/init/Items.java
> +	protected static Item createMekCrystal(MMDMaterial material, CreativeTabs tab) {
Item it -> Item item

Needs oredict stuff put back

2017-04-24 21:36 UTC, jriwanek commented on src/main/java/com/mcmoddev/lib/init/Items.java
> +	protected static Item createMekShard(MMDMaterial material, CreativeTabs tab) {
Item it -> Item item

2017-04-24 21:36 UTC, jriwanek commented on src/main/java/com/mcmoddev/lib/init/Items.java
> +	protected static Item createMekClump(MMDMaterial material, CreativeTabs tab) {
Item it -> Item item

2017-04-24 21:36 UTC, jriwanek commented on src/main/java/com/mcmoddev/lib/init/Items.java
> +	protected static Item createMekDirtyPowder(MMDMaterial material, CreativeTabs tab) {
Item it -> Item item

2017-04-24 21:36 UTC, jriwanek commented on src/main/java/com/mcmoddev/lib/init/Items.java
> +	protected static Item createCasing(MMDMaterial material, CreativeTabs tab) {
Item it -> Item item

2017-04-24 21:36 UTC, jriwanek commented on src/main/java/com/mcmoddev/lib/init/Items.java
> +	protected static Item createDensePlate(MMDMaterial material, CreativeTabs tab) {
Item it -> Item item

2017-04-24 21:36 UTC, jriwanek commented on src/main/java/com/mcmoddev/lib/init/Items.java
> +	protected static Item createCrushed(MMDMaterial material, CreativeTabs tab) {
Item it -> Item item

2017-04-24 21:36 UTC, jriwanek commented on src/main/java/com/mcmoddev/lib/init/Items.java
> +	protected static Item createCrushedPurified(MMDMaterial material, CreativeTabs tab) {
Item it -> Item item

2017-04-24 21:36 UTC, jriwanek commented on src/main/java/com/mcmoddev/lib/init/Items.java
> +	protected static Item createSlab(MMDMaterial material, CreativeTabs tab) {
Needs oredict stuff put back

2017-04-24 21:36 UTC, jriwanek commented on src/main/java/com/mcmoddev/lib/init/Items.java
> +	protected static Item createDoor(MMDMaterial material, CreativeTabs tab) {
Item it -> Item item
Needs oredict stuff put back

2017-04-24 22:48 UTC, TheCodedOne commented
more shit?

2017-04-25 03:55 UTC, jriwanek approved these changes

2017-04-27 18:16 UTC, merged