Master 1.12
MinecraftModDevelopmentMods/BaseMetals pull request #213
Opened 2017-10-02 21:05 UTC by dshadowwolf

Completely tear out and replace a large chunk of the Tinkers' Construct plugin. Some work left - such as moving some fixed-period features to TinkersConstructBase - but this code is otherwise as complete and functional as I can make it. Seems the Tinkers' book isn't adding our Modifiers, but I don't know what can actually be done to resolve this - last attempt flopped.

2017-10-02 21:11 UTC, jriwanek requested changes

2017-10-02 21:11 UTC, jriwanek commented on src/main/java/com/mcmoddev/basemetals/BaseMetals.java
> +		dependencies = "required-after:forge@[14.21.0.2327,);after:taiga;after:tconstruct;after:ic2;before:buildingbricks",
taiga is removed in 1.12, so no need for an after stanza for it

2017-10-02 23:00 UTC, dshadowwolf commented
No fix possible for the "Modifiers not appearing in 'Materials and You'" Only "Materials" and "Bow Materials" are wholly defined in code, the other sections are partially defined as JSON files in the assets of tconstruct.

2017-10-03 19:04 UTC, jriwanek approved these changes

2017-10-03 19:04 UTC, merged