Decoupling of TabContainer
MinecraftModDevelopmentMods/BaseMetals pull request #242
Opened 2017-12-17 22:26 UTC by SkyBlade1978

This PR is to wrap the TabContainer in an interface and ensure that the concrete of the TabContainer is not referenced in code.

The remaining tasks to be completed in the next PR will be;

1) add ItemStack to tab provider interface
2) Implement a dymamic tabProvider
3) remove TabContainer and ItemGroups
4) add common tabs enumeration
5) finalize common tab icon setter

and any other tidy ups..

2017-12-17 22:55 UTC, pau101 requested changes
Minor adjustments to logging and string constants.

2017-12-17 22:55 UTC, pau101 commented on src/main/java/com/mcmoddev/basemetals/proxy/ClientProxy.java
> +			e.printStackTrace();
I would expect `BaseMetals.logger` usage here.

2017-12-17 22:55 UTC, pau101 commented on src/main/java/com/mcmoddev/basemetals/proxy/ClientProxy.java
> +			e.printStackTrace();
And here of course.

2017-12-17 22:55 UTC, pau101 commented on src/main/java/com/mcmoddev/lib/init/Blocks.java
> +				e.printStackTrace();
BM logger here too.

2017-12-17 22:55 UTC, pau101 commented on src/main/java/com/mcmoddev/lib/util/TabContainer.java
> +	private static final String TAB_NOT_FOUND = "Tab not found: ";
Use of this constant for message concatenation is unnecessary with the string appended inside of the `TabNotFoundException` constructor.

2017-12-17 22:55 UTC, pau101 commented on src/main/java/com/mcmoddev/lib/init/Items.java
> +				e.printStackTrace();
BM logger here.

2017-12-17 22:55 UTC, pau101 commented on src/main/java/com/mcmoddev/lib/exceptions/MaterialNotFoundException.java
> +		super(materialName + " was not found in the tab array");
The message appended could be more appropriate to reflect being a material instead of a tab.

2017-12-17 23:06 UTC, dshadowwolf commented
Looks good.

2017-12-17 23:41 UTC, dshadowwolf approved these changes

2017-12-20 22:33 UTC, pau101 requested changes

2017-12-20 22:33 UTC, pau101 commented on src/main/java/com/mcmoddev/lib/util/MMDResourceLocation.java
> +        super( "mmdlib", UUID.nameUUIDFromBytes(String.format("%s:%s/%s", namespace, entryType, entryName).getBytes()).toString() );
Would advise on using `getBytes(Charsets.UTF_8)` to not rely on the default charset.

2017-12-20 22:33 UTC, pau101 commented on src/main/java/com/mcmoddev/lib/util/HashTuple2.java
> +public class HashTuple2<A, B> {
I recommend `final` here.

2017-12-20 22:33 UTC, pau101 commented on src/main/java/com/mcmoddev/basemetals/proxy/ClientProxy.java
> +			BaseMetals.logger.warn(e.toString());
Logging of exceptions should be in this format.
```java
BaseMetals.logger.warn("Failed to foobar", e);
```

2017-12-24 02:14 UTC, merged